
CC := g++
COMPILE_FLAGS := -c -larmadillo
PROGRAMS := Particle.exe PenningTrap.exe main.exe
NAME := penningtrap

compile:
	$(CC) $(FLAGS) particle/Particle.cpp penningtrap/PenningTrap.cpp main.cpp

run:
	./a.out

clean:
	rm -f a.out